### ISSUE TITLE
How to use TabCompleter with your builder?

### ISSUE THREAD

**Issue by Azodox** [LlewVallis/command-builder#1]
Hey, hope you're still active.
I was wondering, how can I deal with TabCompleter with your builder? Do I simply need to implements my class by TabCompleter?

**Comment by LlewVallis** [comment]
Hey @Azodox, tab completion should be handled automatically by the library. If you use the standard argument types like string sets or coordinates, the automatic tab completion provided by command builder should be pretty sensible. If you need more control over the completion of a particular argument to a command, you should create a custom argument type which implements [ArgumentParser](https://github.com/LlewVallis/command-builder/blob/master/src/main/java/io/github/llewvallis/commandbuilder/ArgumentParser.java). Have a look in [this directory](https://github.com/LlewVallis/command-builder/tree/master/src/main/java/io/github/llewvallis/commandbuilder/arguments) for examples of what those implementations should look like. All the best.
